sensors:

  logical_camera_bins0:
    type: logical_camera
    pose:
      xyz: [-2.286283, 2.963994, 1.801095]
      rpy: [3.141593, 1.570792, 0.000000]

  logical_camera_bins1:
    type: logical_camera
    pose:
      xyz: [-2.286283, -2.963994, 1.801095]
      rpy: [3.141593, 1.570792, 0.000000]


  logical_camera_station1:
    type: logical_camera
    pose:
      xyz: [-7.262095, 2.963994, 2.285697]
      rpy: [3.141593, 1.570792, 0.000000]

  logical_camera_station2:
    type: logical_camera
    pose:
      xyz: [-12.26217, 2.963994, 2.285697]
      rpy: [3.141593, 1.570792, 0.000000]

 
  logical_camera_station3:
    type: logical_camera
    pose:
      xyz: [-7.262095, -2.963994, 2.285697]
      rpy: [3.141593, 1.570792, 0.000000]

  logical_camera_station4:
    type: logical_camera
    pose:
      xyz: [-12.26217, -2.963994, 2.285697]
      rpy: [3.141593, 1.570792, 0.000000]

