# Trial Name: assembly.yaml
# ARIAC2023

# ENVIRONMENT SETUP

time_limit: -1 # options: -1 (no time limit) or number of seconds (max 500)

kitting_trays: # Which kitting trays will be spawn
  tray_ids: [1] 
  slots: [4]

parts:  
  bins: # bin params - 8 total bins each bin has nine total slots (1-9)
    bin1:
      - type: 'battery'
        color: 'red'
        slots: [4, 6]
    bin2:
      - type: 'pump'
        color: 'orange'
        slots: [4, 6]
    bin5:
      - type: 'regulator'
        color: 'green'
        slots: [4, 6]
    bin6:
      - type: 'sensor'
        color: 'purple'
        slots: [4, 6]

orders:
  - id: '9RF7SHZN'
    type: 'combined'
    announcement:
      time_condition: 0
    priority: false
    combined_task:
      station: 'as2'
      products:
        - type: 'regulator'
          color: 'green'
          assembled_pose: 
            xyz: [0.175, -0.223, 0.215]
            rpy: ['pi/2', 0, '-pi/2']
          assembly_direction: [0, 0, -1]
        - type: 'battery'
          color: 'red'
          assembled_pose: 
            xyz: [-0.15, 0.035, 0.043]
            rpy: [0, 0, 'pi/2']
          assembly_direction: [0, 1, 0]
        - type: 'pump'
          color: 'orange'
          assembled_pose: 
            xyz: [0.14, 0.0, 0.02]
            rpy: [0, 0, '-pi/2']
          assembly_direction: [0, 0, -1]
        - type: 'sensor'
          color: 'purple'
          assembled_pose: 
            xyz: [-0.1, 0.395, 0.045]
            rpy: [0, 0, '-pi/2']
          assembly_direction: [0, -1, 0]
