# Trial Name: qc.yaml
# ARIAC2023

# ENVIRONMENT SETUP

time_limit: -1 # options: -1 (no time limit) or number of seconds (max 500)

kitting_trays: # Which kitting trays will be spawn
  tray_ids: [3, 8] 
  slots: [1, 4]





parts:  
  bins: # bin params - 8 total bins each bin has nine total slots (1-9)
    bin2:
      - type: 'pump'
        color: 'purple'
        slots: [1, 3, 7, 9]
    bin6:
      - type: 'battery'
        color: 'blue'
        slots: [1, 3, 7, 9]

        
# GLOBAL CHALLENGES
challenges:
  # - human:
  #     behavior: 'helpful'
  #     time_condition: 5.0
  - human:
      behavior: 'antagonistic'
      part_place_condition:
        color: 'blue'
        type: 'battery'
        agv: 4

# ORDERS
orders:
  - id: 'MMB30H56'
    type: 'kitting'
    announcement:
      time_condition: 0
    priority: false
    kitting_task:
      agv_number: 4
      tray_id: 3
      destination: 'warehouse'
      products:
        - type: 'battery'
          color: 'blue'
          quadrant: 1
        - type: 'pump'
          color: 'purple'
          quadrant: 2
  - id: 'MMB30H57'
    type: 'kitting'
    announcement:
      time_condition: 60
    priority: false
    kitting_task:
      agv_number: 1
      tray_id: 8
      destination: 'warehouse'
      products:
        - type: 'battery'
          color: 'blue'
          quadrant: 3
        - type: 'pump'
          color: 'purple'
          quadrant: 4