# ARIAC 2022
# Trial for the faulty sensors challenge.
# Sensors will stop reporting whenever a part is placed either on
# a movable tray or in a briefcase
# Sensors will resume after 20 simulation seconds

options:
  insert_models_over_bins: true
  belt_population_cycles: 0
  insert_models_over_stations: false
  gazebo_state_logging: true
  # mandatory: gripper_tray or gripper_part
  current_gripper_type: gripper_tray
time_limit: -1


# The table_tray_infos is not mandatory
# The different options for tray_model are:
#  -movable_tray_metal_shiny
#  -movable_tray_metal_rusty
#  -movable_tray_dark_wood
#  -movable_tray_light_wood
# quantity can be: 1, 2, or 3
table_tray_infos:
  table_1: 
    tray_model: movable_tray_metal_shiny
    quantity: 1

# mandatory: location of agvs and products at start
agv_infos:
  agv1:
    location: ks1
  agv2:
    location: ks2
  agv3:
    location: ks3
  agv4:
    location: ks4

# Only one order 
orders:
  order_0:
    priority: 1
    kitting_robot_health: 1
    assembly_robot_health: 1 
    # disable_robot: [kitting_robot, agv1, 1] # [kitting_robot, agv1, 1]
    announcement_condition: time
    announcement_condition_value: 0.0
    kitting:
      shipment_count: 1
      trays: [movable_tray_metal_shiny]
      agvs: [agv1]
      destinations: [as1]
      products:
        part_0:
          type: assembly_pump_red
          pose:
            xyz: [-0.1, -0.1, 0.0]
            rpy: [0.0, 0.0, 0.0]

models_over_bins:
   bin2:
     models:
       assembly_pump_red:
         xyz_start: [0.2, 0.2, 0.0]
         xyz_end: [0.4, 0.4, 0.0]
         rpy: [0, 0, 0]
         num_models_x: 2
         num_models_y: 2

sensor_blackout:
  product_count: 1 #sensor blackout triggered after 1 product is placed
  duration: 20

# don't forget to include at least 1 empty line here
