# ARIAC 2022
# This trial requires the gantry robot to place 4 parts in a briefcase located on as2
# An AGV with the needed parts are already located at as2

options:
  insert_models_over_bins: false
  belt_population_cycles: 0
  insert_models_over_stations: true
  gazebo_state_logging: true
  current_gripper_type: gripper_part
time_limit: -1

# The table_tray_infos is mandatory
# The different options for tray_model are:
#  -movable_tray_metal_shiny
#  -movable_tray_metal_rusty
#  -movable_tray_dark_wood
#  -movable_tray_light_wood
# quantity can be: 1, 2, or 3
# table_tray_infos:
#   table_1: 
#     tray_model: movable_tray_metal_shiny
#     quantity: 1
#   table_2: 
#     tray_model: movable_tray_dark_wood
#     quantity: 1

#location of each agv and products on agvs when the simulation starts
agv_infos:
  agv1:
    location: ks1
  agv2:
    location: as2
    products:
      part_0:
        type: assembly_sensor_green
        pose:
          xyz: [0.1, -.15, 0]
          rpy: [0, 0, 0]
      part_1:
        type: assembly_battery_green
        pose:
          xyz: [-0.1, -.15, 0]
          rpy: [0, 0, 0]
      part_2:
        type: assembly_regulator_red
        pose:
          xyz: [-0.1, 0.15, 0]
          rpy: [0, 0, 0]
      part_3:
        type: assembly_pump_blue
        pose:
          xyz: [0.1, 0.15, 0]
          rpy: [0, 0, 0]
  agv3:
    location: ks3
  agv4:
    location: ks4

orders:
  order_0:
    priority: 1
    kitting_robot_health: 1
    assembly_robot_health: 1 
    announcement_condition: time
    announcement_condition_value: 0.0
    assembly:
      shipment_count: 1
      stations: [as2]
      products:
        part_0:
          type: assembly_regulator_red
          pose:
            xyz: [-0.222, -0.164, 0.212]
            rpy: ['pi', 'pi/2', 'pi']
        part_1:
          type: assembly_sensor_green
          pose:
            xyz: [0.405, 0.164, 0.110]
            rpy: ['pi/2', 0, 0]
        part_2:
          type: assembly_battery_green
          pose:
            xyz: [-0.030, 0.180, 0.088]
            rpy: [0, 0, 0]
        part_3:
          type: assembly_pump_blue
          pose:
            xyz: [0.032, -0.153, 0.076]
            rpy: [0, 0, 0]

