options:
  insert_models_over_bins: true
  belt_population_cycles: 20
  gazebo_state_logging: true
time_limit: 500

#location of each agv and products on agvs when the simulation starts
agv_infos:
  agv1:
    location: ks1
  agv2:
    location: ks2
  agv3:
    location: ks3
  agv4:
    location: ks4

# Only one order with two shipments
orders:
  order_0:
    priority: 1
    kitting_robot_health: 1
    assembly_robot_health: 1 
    announcement_condition: time
    announcement_condition_value: 0.0
    kitting:
      shipment_count: 2
      agvs: [agv1, agv4]
      destinations: [as2, as3]
      products:
        part_0:
          type: assembly_battery_red
          pose:
            xyz: [0.1, 0.1, 0]
            rpy: [0, 0, 'pi/4']
        part_1:
          type: assembly_pump_green
          pose:
            xyz: [-0.15, -0.1, 0]
            rpy: [0, 0, 0]


models_over_bins:
   bin2:
     models:
       assembly_battery_red:
         xyz_start: [0.2, 0.2, 0.0]
         xyz_end: [0.4, 0.4, 0.0]
         rpy: [0, 0, 'pi/3']
         num_models_x: 2
         num_models_y: 2


belt_models:
  assembly_pump_green:
    10.0:
      pose:
        xyz: [0.0, 4.3, 0.92]
        rpy: [0, 0, 0]



