# Example sensor configuration with one of each sensor type
sensors:
  breakbeam_0:
    type: break_beam
    visualize_fov: true
    pose:
      xyz: [-0.35, 3, 0.95]
      rpy: [0, 0, pi]

  proximity_sensor_0:
    type: proximity
    visualize_fov: true
    pose:
      xyz: [-0.573, 2.84, 1]
      rpy: [pi/2, pi/6, pi/2]

  laser_profiler_0:
    type: laser_profiler
    visualize_fov: true
    pose:
      xyz: [-0.573, 1.486, 1.526]
      rpy: [pi/2, pi/2, 0]

  lidar_0:
    type: lidar
    visualize_fov: false
    pose:
      xyz: [-2.286, -2.96, 1.8]
      rpy: [pi, pi/2, 0]

  rgb_camera_0:
    type: rgb_camera
    visualize_fov: false
    pose:
      xyz: [-2.286, 2.96, 1.8]
      rpy: [pi, pi/2, 0]

  rgbd_camera_0:
    type: rgbd_camera
    visualize_fov: false
    pose:
      xyz: [-2.286, 4.96, 1.8]
      rpy: [pi, pi/2, 0]

  basic_logical_camera_0:
    visualize_fov: false
    type: basic_logical_camera
    pose:
      xyz: [-2.286, 2.96, 1.8]
      rpy: [pi, pi/2, 0]

  advanced_logical_camera_0:
    visualize_fov: false
    type: advanced_logical_camera
    pose:
      xyz: [-2.286, -2.96, 1.8]
      rpy: [pi, pi/2, 0]
  