#Number of orders: 1
#Tasks: kitting
#Number of shipments: 1
#Insufficiently many products: No
#Part re-orientation: No
#In-process order update: No
#Dropped products: Yes
#In-process order interruption: No
#Faulty products: No
#Sensor blackout: No
#Time limit: No
options:
  insert_models_over_bins: true
  insert_models_over_shelves: true
  belt_population_cycles: 0
  time_limit: -1

#location of each agv and products on agvs when the simulation starts
agv_infos:
  agv1:
    location: ks1
  agv2:
    location: ks2
  agv3:
    location: ks3
  agv4:
    location: ks4

orders:
  order_0:
    priority: 1
    kitting_robot_health: 1
    assembly_robot_health: 1 
    announcement_condition: time
    announcement_condition_value: 0.0
    kitting:
      shipment_count: 1
      agvs: [agv3]
      destinations: [as3]
      products:
        part_0:
          type: assembly_battery_blue
          pose:
            xyz: [0.1, 0.1, 0]
            rpy: [0, 0, 0]
        part_1:
          type: assembly_regulator_red
          pose:
            xyz: [0.15, 0.1, 0]
            rpy: [0, 0, 0]
        part_2:
          type: assembly_sensor_blue
          pose:
            xyz: [-0.1, -0.1, 0]
            rpy: [0, 0, 0]

models_over_bins:
   bin3:
     models:
       assembly_battery_blue:
         xyz_start: [0.2, 0.2, 0.0]
         xyz_end: [0.4, 0.4, 0.0]
         rpy: [0, 0, 0]
         num_models_x: 2
         num_models_y: 2
   bin4:
     models:
       assembly_regulator_red:
         xyz_start: [0.1, 0.2, 0.0]
         xyz_end: [0.4, 0.5, 0.0]
         rpy: [0, 0, 'pi/4']
         num_models_x: 2
         num_models_y: 2
   bin5:
     models:
       assembly_sensor_blue:
         xyz_start: [0.1, 0.2, 0.0]
         xyz_end: [0.4, 0.5, 0.0]
         rpy: [0, 0, 'pi/4']
         num_models_x: 2
         num_models_y: 2


drops:
  drop_regions:
    shipping_box_0_impeding:
      frame: agv3::kit_tray_3
      min:
        xyz: [-0.3, -0.3, 0.0]
      max:
        xyz: [0.3, 0.3, 0.5]
      destination:
        xyz: [0.2, 0.3, 0.05]
        rpy: [0, 0, 0.2]
      product_type_to_drop: assembly_regulator_red
    shipping_box_1_impeding:
      frame: agv3::kit_tray_3
      min:
        xyz: [-0.3, -0.3, 0.0]
      max:
        xyz: [0.3, 0.3, 0.5]
      destination:
        xyz: [0.2, 0.3, 0.05]
        rpy: [0, 0, 0.2]
      product_type_to_drop: assembly_sensor_blue


