#Number of orders: 1
#Tasks: kitting
#Number of shipments: 1
#Insufficiently many products: No
#Part re-orientation: No
#In-process order update: No
#Dropped products: No
#In-process order interruption: No
#Faulty products: Yes
#Sensor blackout: No
#Time limit: No
options:
  insert_models_over_bins: false
  insert_models_over_stations: false
  belt_population_cycles: 5
  visualize_drop_regions: true
time_limit: -1

agv_infos:
  agv1:
    location: ks1
  agv2:
    location: ks2
  agv3:
    location: ks3
  agv4:
    location: ks4
    
orders:
  # Example for tasking one robot to do assembly and one robot to do kitting
  order_0:
    priority: 1
    kitting_robot_health: 1
    assembly_robot_health: 1
    announcement_condition: time
    announcement_condition_value: 0.0
    kitting:
      shipment_count: 1
      agvs: [agv2]
      destinations: [as1]
      products:
        part_0:
          type: assembly_battery_blue
          pose:
            xyz: [0.15, 0.1, 0]
            rpy: [0, 0, 0]
        part_1:
          type: assembly_battery_blue
          pose:
            xyz: [-0.15, -0.1, 0]
            rpy: [0, 0, 0]
          
models_over_bins:
  bin3:
    models:
      assembly_sensor_blue:
        xyz_start: [0.2, 0.2, 0.0]
        xyz_end: [0.4, 0.4, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 2
        num_models_y: 1

belt_models:
  assembly_sensor_blue:
    10.0:
      pose:
        xyz: [0.0, 4.3, 0.92]
        rpy: [0, 0, 'pi/2']

# sensor_blackout:
#   product_count: 2 #sensor blackout triggered after second product is placed
#   duration: 50

# drops:
#   drop_regions:
#     shipping_box_0_impeding:
#       frame: agv3::kit_tray_3
#       min:
#         xyz: [-0.3, -0.3, 0.0]
#       max:
#         xyz: [0.3, 0.3, 0.5]
#       destination:
#         xyz: [0.1, 0.3, 0.05]
#         rpy: [0, 0, 0.2]
#       product_type_to_drop: assembly_battery_blue
    # shipping_box_1_impeding:
    #   frame: agv3::kit_tray_3
    #   min:
    #     xyz: [-0.3, -0.3, 0.0]
    #   max:
    #     xyz: [0.3, 0.3, 0.5]
    #   destination:
    #     xyz: [0.2, 0.3, 0.05]
    #     rpy: [0, 0, 0.2]
    #   product_type_to_drop: assembly_sensor_blue

# faulty_products:
#   - assembly_battery_blue_2
#   - assembly_regulator_red_1
